# Generated by Django 2.2.4 on 2019-08-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
